# Набор запросов для проверки API через VSCode REST Client.

@host = http://localhost:8000
@token = paste_token_here

###

# Регистрируем продавца
POST {{host}}/api/v1/seller HTTP/1.1
Content-Type: application/json

{
    "first_name": "Ivan",
    "last_name": "Petrov",
    "e_mail": "seller@example.com",
    "password": "secret"
}

###

# Получаем JWT токен
POST {{host}}/api/v1/token HTTP/1.1
Content-Type: application/json

{
    "e_mail": "seller@example.com",
    "password": "secret"
}

###

# Получаем список продавцов
GET {{host}}/api/v1/seller HTTP/1.1

###

# Получаем продавца с книгами
GET {{host}}/api/v1/seller/1 HTTP/1.1
Authorization: Bearer {{token}}

###

# Обновляем продавца без пароля и книг
PUT {{host}}/api/v1/seller/1 HTTP/1.1
Content-Type: application/json

{
    "first_name": "Petr",
    "last_name": "Ivanov",
    "e_mail": "new-seller@example.com"
}

###

# Создаем книгу
POST {{host}}/api/v1/books/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Clean Architecture",
    "author": "Robert Martin",
    "count_pages": 300,
    "year": 2025,
    "seller_id": 1
}

###

# Получаем список книг
GET {{host}}/api/v1/books/ HTTP/1.1

###

# Получаем одну книгу по ее ИД
GET {{host}}/api/v1/books/1 HTTP/1.1

###

# Обновляем книгу
PUT {{host}}/api/v1/books/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 1,
    "title": "Clean Code",
    "author": "Robert Martin",
    "year": 2024,
    "pages": 310,
    "seller_id": 1
}

###

# Частично обновляем книгу
PATCH {{host}}/api/v1/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Mziri",
    "pages": 320
}

###

# Удаляем книгу
DELETE {{host}}/api/v1/books/1 HTTP/1.1

###

# Удаляем продавца вместе с его книгами
DELETE {{host}}/api/v1/seller/1 HTTP/1.1
